README.md, src/SampleApp/SampleApp.csproj, src/WinUI.TableView/CommunityToolkit.WinUI.Collections/AdvancedCollectionView.CollectionChangedListener.cs, src/WinUI.TableView/CommunityToolkit.WinUI.Collections/AdvancedCollectionView.cs, src/WinUI.TableView/Converters/BoolToVisibilityConverter.cs, src/WinUI.TableView/TableViewColumnHeader.cs, src/WinUI.TableView/TableViewHeaderRow.cs, src/WinUI.TableView/Themes/Generic.xaml, src/WinUI.TableView/WinUI.TableView.csproj
removed dependencies:
- CommunityToolkit.WinUI.Helpers 
- CommunityToolkit.WinUI.Converters 
- CommunityToolkit.WinUI.Controls.Sizers
=> remove dependencies

src/WinUI.TableView/TableView.cs, src/WinUI.TableView/TableViewCell.cs, src/WinUI.TableView/TableViewColumn.cs, src/WinUI.TableView/TableViewColumnHeader.OptionsFlyoutViewModel.cs, src/WinUI.TableView/TableViewColumnHeader.cs, src/WinUI.TableView/Themes/TableViewColumnHeader.xaml
* fixed column header resize are issue when CanFilter set to false
* improved column filter behavior & UI
* changed default HeaderRowWidth from 48 to 32
* make the vertical scrollbar to display under the header row
* fixed an issue where column resize was using next columns max & min width
* implemented auto resizing column by double clicking on resize area
=> merge dev branch into main

src/WinUI.TableView/TableViewCell.cs, src/WinUI.TableView/TableViewComboBoxColumn.cs
fixes #15 
introducing new properties in ComboBoxColumn
* `IsEditable` makes the ComboBox editable.
* `TextBidning` allow to bind ComboBox.Text property
* `SelectedValueBinding` allow to bind ComboBox.SelectedValue.
=> introduced new properties to ComboBoxColumn

src/WinUI.TableView/TableView.cs
=> resolved a null reference exception when visibility was set to collapsed at startup

src/WinUI.TableView/TableView.Properties.cs, src/WinUI.TableView/TableView.cs, src/WinUI.TableView/TableViewCell.cs, src/WinUI.TableView/TableViewColumn.cs, src/WinUI.TableView/TableViewComboBoxColumn.cs, src/WinUI.TableView/TableViewHeaderRow.cs, src/WinUI.TableView/TableViewRow.cs, src/WinUI.TableView/TableViewTemplateColumn.cs, src/WinUI.TableView/TableViewToggleSwitchColumn.cs
this PR includes changes suggested in issue #43.
=> make dependency reference type properties as nullable

src/WinUI.TableView/TableView.cs
=> bind row height property to the TableView.RowHeight

src/WinUI.TableView/TableViewColumn.cs
=> added Tag property

src/Directory.Build.props, src/SampleApp/SampleApp.csproj, src/WinUI.TableView/ColumnFilterHandler.cs, src/WinUI.TableView/Columns/TableViewColumn.cs, src/WinUI.TableView/Controls/TableViewTimePicker.cs, src/WinUI.TableView/Converters/BoolToVisibilityConverter.cs, src/WinUI.TableView/Extensions/ObjectExtensions.cs, src/WinUI.TableView/ItemsSource/CollectionView.cs, src/WinUI.TableView/ItemsSource/VectorChangedEventArgs.cs, src/WinUI.TableView/TableView.Properties.cs, src/WinUI.TableView/TableView.cs, src/WinUI.TableView/TableViewCell.cs, src/WinUI.TableView/TableViewCellsPresenter.cs, src/WinUI.TableView/TableViewColumnHeader.OptionsFlyoutViewModel.cs, src/WinUI.TableView/TableViewColumnsCollection.cs, src/WinUI.TableView/TableViewHeaderRow.cs, src/WinUI.TableView/TableViewRow.cs, src/WinUI.TableView/WinUI.TableView.csproj
- upgraded to .NET8.
- upgraded Microsoft.WindowsAppSDK to 1.6.250108002
- upgraded  CommunityToolkit.WinUI.Behaviors to 8.1.240916
=> upgrade to .NET8

src/ColumnFilterHandler.cs, src/Columns/TableViewDateColumn.cs, src/Columns/TableViewTimeColumn.cs, src/Strings/en-US/WinUI.TableView.resw, src/TableViewColumnHeader.OptionsFlyoutViewModel.cs, src/TableViewColumnHeader.cs, src/TableViewHeaderRow.OptionsFlyoutViewModel.cs, src/TableViewLocalizedStrings.cs, src/Themes/TableViewColumnHeader.xaml
This PR introduces localization support for **WinUI.TableView**, allowing users to add resource files for their desired languages. This was a long-awaited enhancement request, and it is now implemented.  
- Added support for localization using `.resw` files.  
- Users can now add a resource file named `WinUI.TableView.resw` under `Strings/{language name}/`.  
- Set desired language to  `Microsoft.Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride`
Sample resources:
| Name                                 | en-US                                               |
|--------------------------------------|-----------------------------------------------------|
| BlankFilterValue                     | (Blank)                                            |
| Cancel …
=> added localization support

src/Strings/de-DE/WinUI.TableView.resw
add a new .resw for strings/de-DE.
=> Locale for de-DE

src/Columns/TableViewDateColumn.cs, src/Columns/TableViewTimeColumn.cs
=> changed default types for date and time column

src/TableViewLocalizedStrings.cs
Use `ResourceManager` for WinUI and `ResourceLoader` for Uno.
Closes #125
=> use resource manager for WinUI

src/Strings/ru-RU/WinUI.TableView.resw
=> Add .resw for ru-RU

src/Extensions/ItemIndexRangeExtensions.cs, src/TableView.cs, src/TableViewCell.cs, src/TableViewHeaderRow.cs, src/TableViewRow.cs, src/Tableview.Uno.cs, src/Themes/TableViewCellsPresenter.xaml, src/Themes/TableViewRow.xaml
- Ensure rows are selectable on Uno platform.
- Ensure multi select checkbox available for Uno.
- Ensure multiple cells are selectable with mouse on Uno.
fixes #141
=> fixed row and cell selection on Uno platform

src/TableViewCell.cs
=> avoid redundant row selection

src/Columns/TableViewColumn.cs, src/Columns/TableViewTemplateColumn.cs, src/TableViewCell.cs
=> fixed template column template selector issues

src/Extensions/ObjectExtensions.cs
@w-ahmad  for my personal use, I ran into limitations for more complex binding paths.
My specific use case is binding to a property that returns an array, which I index over, e.g.:  `MyFields[2].Value`
`MyFields` is a property, so straight up indexing on it with the PropertyInfo (with the 1.3.1 version) did not work (failed at this code `pi?.GetValue(obj, [index])` since the PropertyInfo does not support it).
Changed the code to support (besides the default object indexer) any indexer on a Arrays, IList, whether they are encapsulated as a Property or directly exposed as a public field.
However :-) only just noticed that you _too_ added support for arrays: https://github.com/w-ahmad/WinUI.TableView/commit/417ae329eb24594c0cbdd3eefe1dde0ba6b0cbb0
Not sure what you want to do (keep your …
=> Support for more advanced path definitions

src/TableViewColumnHeader.cs
fixes #136 
This PR introduces defer refresh on sorting so the TableView won't reset horizontal scroll offset.
https://github.com/user-attachments/assets/2179d027-335b-4916-8e05-31d4b89005fe
=> added defer refresh on sorting to keep h scroll offset

src/TableView.Properties.cs, src/TableViewCell.cs, src/TableViewCellsPresenter.cs
=> fixed cell and row measure issues

src/Columns/TableViewColumn.cs, src/EventArgs/TableViewAutoGeneratingColumnEventArgs.cs, src/Extensions/ObjectExtensions.cs, src/Extensions/TypeExtensions.cs, src/TableView.Properties.cs, src/TableView.cs, src/TableViewColumnsCollection.cs, src/TableViewHeaderRow.cs, src/TableViewRow.cs
- Improved auto generate column process. 
- Make sure [DisplayAttribute.AutoGenerateFilter](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.autogeneratefilter) works properly.
- Make sure [DisplayAttribute.Order](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.order) works properly.
- Introduced `Order` property for columns to change the display order.
=> improved auto generate column process

src/Strings/ru-RU/WinUI.TableView.resw
=> Fix .resw for ru-RU

src/WinUI.TableView.csproj
=> added WebView2 package explicitly

src/TableView.cs
=> set cell & row flyout's datacontexts to backing item on Uno

src/TableView.cs
@w-ahmad 
I've integrated Refresh and RefreshSorting into the TableView.
This makes it possible to update or sort the TableView through code. 
You can take a look and see if it makes sense for you.
=> Refresh and RefreshSorting available in Tableview
